id: AEA68E205
base_file: fCA11.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:35:07.005756
  last_modified_at: 2022-05-30 18:35:07.005762
